# General configuration.
title: Error Prone Support
logo: assets/images/favicon.svg
url: https://error-prone.picnic.tech
description: >-
  Error Prone extensions: extra bug checkers and a large battery of Refaster
  rules.

theme: just-the-docs
plugins:
  - jekyll-sitemap

# Files and directories not to be deployed through GitHub pages.
exclude:
  - Gemfile
  - Gemfile.lock
  - generate-version-compatibility-overview.sh
  - README.md
  - vendor

# See https://jekyllrb.com/docs/permalinks/#built-in-formats.
permalink: pretty

# Theme (just-the-docs) configuration.
# See
# https://just-the-docs.github.io/just-the-docs/docs/navigation-structure/#external-navigation-links.
nav_external_links:
  - title: Error Prone Support on GitHub
    url: https://github.com/PicnicSupermarket/error-prone-support
    hide_icon: false

callouts:
  summary:
    color: blue
  note:
    color: grey-dk

# SEO configuration.
# See https://jekyll.github.io/jekyll-seo-tag/usage.
social:
  name: Picnic
  links:
    - https://github.com/PicnicSupermarket
    - https://twitter.com/picnic
    - https://www.linkedin.com/company/picnictechnologies
twitter:
  username: picnic
  card: summary
