# General configuration.
title: Error Prone Support
logo: assets/images/favicon.svg
url: https://error-prone.picnic.tech/
description: >-
  Error Prone Support is a Picnic-opinionated extension of Google's Error
  Prone. It aims to improve code quality, focussing on maintainability,
  consistency and avoidance of common gotchas.

remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-theme

# Do not deploy through GitHub pages.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

permalink: pretty # Use /doc/ vs. /doc.html

# Theme configuration.
search_enabled: true
heading_anchors: true

callouts:
  summary:
    title: Summary
    color: blue
  warning:
    title: Warning
    color: red

nav_external_links:
  - title: Error Prone Support on GitHub
    url: https://github.com/PicnicSupermarket/error-prone-support
    hide_icon: false

twitter:
  username: picnic
  card: summary

social:
  name: Picnic
  links:
    - https://github.com/PicnicSupermarket
    - https://twitter.com/picnic
    - https://www.linkedin.com/company/picnictechnologies
