name: Update `error-prone.picnic.tech` website contents
on:
  push:
    #branches: [$default-branch]
    branches:
      - 'sschroevers/deploy-to-github-pages'
      - 'gdejong/docgen'
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3.0.2
      - name: Set up JDK
        uses: actions/setup-java@v3.4.1
        with:
          java-version: 11.0.16
          distribution: temurin
          cache: maven
      - name: Configure Github Pages
        uses: actions/configure-pages@v2.0.0
      - name: Generate documentation
        run:  bash ./generate-docs.sh
      - name: Build website with Jekyll
        uses: actions/jekyll-build-pages@v1.0.5
        with:
          source: website/
          destination: ./_site
      - name: Upload website artifact
        uses: actions/upload-pages-artifact@v1.0.3
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.0.9
